name = "PoliSpectralTools"
uuid = "e5870fb4-0785-4c2b-93f1-21089c9623d1"
version = "0.2.0"
authors = ["Course Staff <spectral@example.com>"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"

[compat]
FFTW = "1"
Plots = "1.41.2"
ToeplitzMatrices = "0.8"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b50"

[targets]
test = ["Test"]
