name = "SpectralTools"
uuid = "fca48333-7434-41b0-8f56-a17c12755e8d"
authors = ["osval "]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialPolynomials = "a25cea48-d430-424a-8ee7-0d3ad3742e9e"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"
